name: flutter_proj
description: Coursework

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  sqflite:
  path:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider:
  shared_preferences:
  path_provider:
  http:
  html:
  file_picker:
  animated_theme_switcher:
  syncfusion_flutter_calendar:
  flutter_speed_dial:
  intl:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  generate: true
  fonts:
    - family: Montserrat-Italic
      fonts:
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
          style: normal
    - family: Montserrat-Light
      fonts:
        - asset: fonts/Montserrat-Light.ttf
          style: normal
    - family: Montserrat-SemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
          style: normal
    - family: Montserrat-Regular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: normal
    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

  uses-material-design: true
